-- +goose Up

ALTER TABLE gauges ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE counters ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- +goose Down

ALTER TABLE gauges DROP COLUMN IF EXISTS updated_at;
ALTER TABLE counters DROP COLUMN IF EXISTS updated_at;